### ISSUE TITLE
Bug in cert.json from eudgc project which seems to be generated from trustlist.ts

### ISSUE THREAD

**Issue by Kavboy** [Scopevisio/undoapp-backend#1]
We have noticed an error in the generated cert.json from eugdc project.
The notbefore and notafter millisecond timestamps are wrong in some certs.

In the provided example from the cert.json the notbefore and notafter have the wrong year if we convert the milliseconds back, instead of 2021 they are from 2001 and that is definitly not correct.

Example from cert.json:
` {
     "issuer": "C = DE, O = D-Trust GmbH, CN = D-TRUST CA 2-2 2019, 2.5.4.97 = NTRDE-HRB74346",
     "subject": "C = DE, O = Robert Koch-Institut, OU = Elektronischer Impfnachweis, CN = Robert Koch-Institut, L = Berlin, postalCode = 13353, street = Nordufer 20, 2.5.4.97 = DT:DE-3023531445, serialNumber = CSM026382968, ST = Berlin\nSubject Public Key Info:",
            "notbefore": 991558373000,
            "notafter": 991903973000,
            "pubkey": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgMhpOktfDD7Vn7Wm+BlHabFbpOs2\nUmCVrtIpcOFpIlr8+2wHP5/VSUZslExSo284fpwuoJ5eKcjDuvlCPjZNhQ==\n-----END PUBLIC KEY-----\n",
            "rawX509data": "MIIHUTCCBQmgAwIBAgIQTrNSYxxkgkYkdCLUyN9QuTA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCA6EaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgOiAwIBQDBbMQswCQYDVQQGEwJERTEVMBMGA1UEChMMRC1UcnVzdCBHbWJIMRwwGgYDVQQDExNELVRSVVNUIENBIDItMiAyMDE5MRcwFQYDVQRhEw5OVFJERS1IUkI3NDM0NjAeFw0yMTA2MDMxMDUyNTNaFw0yMzA2MDcxMDUyNTNaMIHrMQswCQYDVQQGEwJERTEdMBsGA1UEChMUUm9iZXJ0IEtvY2gtSW5zdGl0dXQxJDAiBgNVBAsTG0VsZWt0cm9uaXNjaGVyIEltcGZuYWNod2VpczEdMBsGA1UEAxMUUm9iZXJ0IEtvY2gtSW5zdGl0dXQxDzANBgNVBAcTBkJlcmxpbjEOMAwGA1UEEQwFMTMzNTMxFDASBgNVBAkTC05vcmR1ZmVyIDIwMRkwFwYDVQRhExBEVDpERS0zMDIzNTMxNDQ1MRUwEwYDVQQFEwxDU00wMjYzODI5NjgxDzANBgNVBAgTBkJlcmxpbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIDIaTpLXww+1Z+1pvgZR2mxW6TrNlJgla7SKXDhaSJa/PtsBz+f1UlGbJRMUqNvOH6cLqCeXinIw7r5Qj42TYWjggLpMIIC5TAfBgNVHSMEGDAWgBRxEDKudHF7VI7x1qtiVK78PsC7FjAtBggrBgEFBQcBAwQhMB8wCAYGBACORgEBMBMGBgQAjkYBBjAJBgcEAI5GAQYCMIH+BggrBgEFBQcBAQSB8TCB7jA3BggrBgEFBQcwAYYraHR0cDovL2QtdHJ1c3QtY2EtMi0yLTIwMTkub2NzcC5kLXRydXN0Lm5ldDBCBggrBgEFBQcwAoY2aHR0cDovL3d3dy5kLXRydXN0Lm5ldC9jZ2ktYmluL0QtVFJVU1RfQ0FfMi0yXzIwMTkuY3J0MG8GCCsGAQUFBzAChmNsZGFwOi8vZGlyZWN0b3J5LmQtdHJ1c3QubmV0L0NOPUQtVFJVU1QlMjBDQSUyMDItMiUyMDIwMTksTz1ELVRydXN0JTIwR21iSCxDPURFP2NBQ2VydGlmaWNhdGU/YmFzZT8wcAYDVR0gBGkwZzAJBgcEAIvsQAEBMFoGCysGAQQBpTQCgRYFMEswSQYIKwYBBQUHAgEWPWh0dHA6Ly93d3cuZC10cnVzdC5uZXQvaW50ZXJuZXQvZmlsZXMvRC1UUlVTVF9DU01fUEtJX0NQUy5wZGYwgfAGA1UdHwSB6DCB5TCB4qCB36CB3IZpbGRhcDovL2RpcmVjdG9yeS5kLXRydXN0Lm5ldC9DTj1ELVRSVVNUJTIwQ0ElMjAyLTIlMjAyMDE5LE89RC1UcnVzdCUyMEdtYkgsQz1ERT9jZXJ0aWZpY2F0ZXJldm9jYXRpb25saXN0hjJodHRwOi8vY3JsLmQtdHJ1c3QubmV0L2NybC9kLXRydXN0X2NhXzItMl8yMDE5LmNybIY7aHR0cDovL2Nkbi5kLXRydXN0LWNsb3VkY3JsLm5ldC9jcmwvZC10cnVzdF9jYV8yLTJfMjAxOS5jcmwwHQYDVR0OBBYEFOUf3iWd2Hum+D068MgwNqU55MGHMA4GA1UdDwEB/wQEAwIGwDA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCA6EaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgOiAwIBQAOCAgEAgNEC7rkQnh/72wrtGhZx/A5dHXieX5Kp4VM6uAS+AnZE/WHsDsg6tOB/8jD6hAAHOAemg0GgUHrpM/A4uwTX/9lJtXF/p+3Eiv54keF2qnv9cZybLmZL6rC7OytA7x3ElhFxfV1SumRqikW5ddb7H/zAeykKTckomWNG2PEDwB3F5HF5L8MGOYmqEI1X+mdI8d7L+4E2z5OXYjB0vh6n+R05MD23LM8EEfN/WkV44toLVAp/tLpln4MmE6sVhXkx2p7LqyRzzOyBI46lccBqGgriWm5rJre9YYO0Il7jAFC1SJNxmTtGxwK9VebxzNeqlVE9lVv/iRSQu+1FwJ5yqUGLjYUbbWTA1U6TV5kgLg7MO3ThBrUVkJDw7f5xewuXfWXueFDW94lS7Er+xsXiHPqsOqDrbDqc+GwcZK5lCKTt/df2W6lWWXR+TFyqI6CEcjFLnzV1t+BuRnyhZcIYcUyNDPUVw7cuh81eN4jORCKXwvThRd3CAFIn8F28/C487aAQDPXTFCL0xpPbbNaN/AqUY5LWGfCuUWrVnVCaOCPfmCijHbKMYjbebybicostdndQl2PfWdCxNSIV2QSTvgiOSYnL8LcV1crE9eoeXN0CYFgj+phNveOwXrA4N8mXIe2uQfW7gKW4vqS0um0fdPeu539Hhpp8sI2LdsEh7EA="
        },`

**Comment by srutz** [comment]
sorry about that one. mistake/unexpected data when parsing the output of openssl, debatable practise from my side anyhow. in any case, the bug was fixed. you need to delete all certs from your database and restart the server for a new fetch with correct dates
